[{"name": "test.test_sum_equation.SumEquation.test_empty", "status": "failed", "message": "'' != '0 = 0'\n+ 0 = 0\n : Incorrect result for an empty input list!", "passed": false, "points": ["p01-19.1"], "backtrace": ["  File \"/usr/lib/python3.12/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.12/unittest/case.py\", line 634, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.12/unittest/case.py\", line 589, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"/home/marco/python-data-analysis-helsinki/01-python/mooc-data-analysis-with-python-2024-2025/part01-e19_sum_equation/test/test_sum_equation.py\", line 40, in test_empty\n    self.assertEqual(result, \"0 = 0\", msg=\"Incorrect result for an empty input list!\")\n"]}, {"name": "test.test_sum_equation.SumEquation.test_first", "status": "failed", "message": "'' != '1 + 5 + 7 = 13'\n+ 1 + 5 + 7 = 13\n : Incorrect result for input list [1, 5, 7]!", "passed": false, "points": ["p01-19.1"], "backtrace": ["  File \"/usr/lib/python3.12/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.12/unittest/case.py\", line 634, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.12/unittest/case.py\", line 589, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"/home/marco/python-data-analysis-helsinki/01-python/mooc-data-analysis-with-python-2024-2025/part01-e19_sum_equation/test/test_sum_equation.py\", line 23, in test_first\n    self.assertEqual(result, \"1 + 5 + 7 = 13\", msg=\"Incorrect result for input list %s!\" % L)\n"]}, {"name": "test.test_sum_equation.SumEquation.test_random", "status": "failed", "message": "None is not true", "passed": false, "points": ["p01-19.1"], "backtrace": ["  File \"/usr/lib/python3.12/unittest/case.py\", line 58, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.12/unittest/case.py\", line 634, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.12/unittest/case.py\", line 589, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"/home/marco/python-data-analysis-helsinki/01-python/mooc-data-analysis-with-python-2024-2025/part01-e19_sum_equation/test/test_sum_equation.py\", line 30, in test_random\n    self.assertTrue(m)\n"]}]